# Generated by Django 6.1 on 2026-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('amber', 'Amber'), ('emerald', 'Emerald'), ('blue', 'Blue'), ('violet', 'Violet')], default='green', max_length=10),
        ),
    ]
